# Generated by Django 2.2.13 on 2021-01-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='pen_make',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pen',
            name='pen_code',
            field=models.CharField(max_length=4),
        ),
    ]
