# Generated by Django 2.2.13 on 2021-02-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='pen',
            name='details',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='pen',
            name='pen_code',
            field=models.CharField(max_length=100),
        ),
    ]
