# Generated by Django 2.2.13 on 2021-02-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_forms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='type',
            new_name='manufacturer',
        ),
    ]
