# Generated by Django 2.2.13 on 2021-10-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_pen_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useCase', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pen',
            name='categories',
            field=models.ManyToManyField(to='accounts.Categories'),
        ),
    ]
